name: Master Branch Validation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            coverage: linux-cov.xml
            executable: grant-linux-amd64
          - os: macos-latest
            coverage: macos-cov.xml
            executable: grant-macos-amd64
          - os: windows-latest
            coverage: windows-cov.xml
            executable: grant-windows-amd64.exe
        python-version: [3.8]
    env:
      DISPLAY: ":99.0"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup 'libxkbcommon-x11-0'
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install libxkbcommon-x11-0
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov
      - name: Run unit tests
        run: |
          pytest --cov=grant --cov-report xml:${{matrix.coverage}} --cov-fail-under=90 tests/
      - name: Check for issues
        run: |
          pylint -E grant
      - name: Validate formatting
        run: |
          black --check grant
      - name: Assemble resource file
        run: |
          pyrcc5 grant.qrc -o resources.py
      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --name ${{matrix.executable}} grant.py 
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.coverage}}
          path: .
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.executable}}
          path: ./dist/
        
        
        
        
        
