name: Master Branch Validation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            coverage: linux-cov.xml
          - os: macos-latest
            coverage: macos-cov.xml
          - os: windows-latest
            coverage: windows-cov.xml
    env:
      DISPLAY: ":99.0"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Setup 'libxkbcommon-x11-0'
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install libxkbcommon-x11-0
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          pytest --cov=grant --cov-report xml:cov.xml --cov-fail-under=90 tests/unit
      - name: Run workflow tests
        run: |
          pytest tests/workflow
      - name: Check for issues
        run: |
          pylint -E grant
      - name: Validate formatting
        run: |
          black --check grant
      - uses: actions/upload-artifact@v2
        name: Upload coverage report for ${{matrix.os}}
        with:
          name: ${{matrix.coverage}}
          path: cov.xml
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            executable: grant-linux-amd64
          - os: macos-latest
            executable: grant-macos-amd64
          - os: windows-latest
            executable: grant-windows-amd64.exe
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Assemble resource file
        run: |
          pyrcc5 grant.qrc -o resources.py
      - name: Build executable
        run: |
          pyinstaller --icon=icons/grant.ico --onefile --windowed --name ${{matrix.executable}} main.py
      - uses: actions/upload-artifact@v2
        name: Upload executable for ${{matrix.os}}
        with:
          name: ${{matrix.executable}}
          path: ./dist/${{matrix.executable}}
